version: "3.3"

services:
  db:
    image: postgres:latest
    ports:
      - '5434:5434'
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    ports: 
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/webapp

volumes:
  dbdata: